# Generated by Django 4.1.4 on 2023-07-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('enrollment_id', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(default='password123', max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='imagestore/')),
            ],
        ),
    ]
