# Generated by Django 4.1.4 on 2023-07-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0002_advocates'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='website',
            field=models.BooleanField(default=False),
        ),
    ]
